import 'package:shared_preferences/shared_preferences.dart';

import 'Preferences.dart';

class Internationalization {


  static SharedPreferences _prefs;

  static String _language = 'en';


  static setPreferences() async {
    _prefs = await SharedPreferences.getInstance();
    if(_prefs.get('lang') != null) {
      _language = _prefs.get('lang');
    }
  }


  static Map<String, Map<String, String>> values = {
    'en': {
      'Welcome': 'Welcome',
      'Username': 'Username',
      'Empty usernames not allowed' : 'Empty usernames not allowed',
      'Password' : 'Password',
      'Empty password not allowed': 'Empty password not allowed',
      'wrong username or password' : 'wrong username or password',
      'Sign in' : 'Sign in',
      'Don\'t have an account?' : 'Don\'t have an account?',
      'Sign up' : 'Sign up',
      'Register' : 'Register',
      'First Name' : 'First Name',
      'Empty first names not allowed' : 'Empty first names not allowed',
      'Last Name' : 'Last Name',
      'Empty last name not allowed' : 'Empty last name not allowed',
      'Empty username not allowed' : 'Empty username not allowed',
      'username exists' : 'username exists',
      'Mobile' : 'Mobile',
      'invalid phone number' : 'invalid phone number',
      'Repeat password' : 'Repeat password',
      'Passwords don\'t match' : 'Passwords don\'t match',
      'Neighborhoods' : 'Neighborhoods',
      'Profile' : 'Profile',
      'Sign Out' : 'Sign Out',
      'MY NEIGHBORHOODS' : 'MY NEIGHBORHOODS',
      'OTHER NEIGHBORHOODS' : 'OTHER NEIGHBORHOODS',
      'SEND REQUEST' : 'SEND REQUEST',
      'PENDING' : 'PENDING',
      'GENERAL INFO' : 'GENERAL INFO',
      'ITEMS' : 'ITEMS',
      'USERNAME' : 'USERNAME',
      'FIRST NAME' : 'FIRST NAME',
      'LAST NAME' : 'LAST NAME',
      'PHONE NUMBER' : 'PHONE NUMBER',
      'Edit' : 'Edit',
      'SAVE' : 'SAVE',
      'Wrong Number' : 'Wrong Number',
      'Malformed phone number' : 'Malformed phone number',
      'CANCEL' : 'CANCEL',
      'ADD' : 'ADD',
      'CAR PLATE NUMBER' : 'CAR PLATE NUMBER',
      'Invalid Action' : 'Invalid Action',
      'Add Item' : 'Add Item',
      'Add new item' : 'Add new item',
      'Item name' : 'Item name',
      'Delete Item' : 'Delete Item',
      'Do you really want to remove this item?' : 'Do you really want to remove this item?',
      'Yes' : 'Yes',
      'No' : 'No',
      'malformed plate number' : 'malformed plate number',
      'Requests' : 'Requests',
      'Profile' : 'Profile',
      'Tasks' : 'Tasks',
      'Search Items' : 'Search Items',
      'Search Car' : 'Search Car',
      'What\'s on your mind? ' : 'What\'s on your mind? ',
      'Post' : 'Post',
      'Write your comment here' : 'Write your comment here',
      ' wants to join the neighborhood' : ' wants to join the neighborhood',
      'ACCEPT' : 'ACCEPT',
      'REJECT' : 'REJECT',
      'REJECTED' : 'REJECTED',
      'ACCEPTED' : 'ACCEPTED',
      'Create Neighborhood' : 'Create Neighborhood',
      'Name' : 'Name',
      'Empty names not allowed' : 'Empty names not allowed',
      'neighborhood already exists' : 'neighborhood already exists',
      'city' : 'city',
      'Empty ciy names not allowed' : 'Empty ciy names not allowed',
      'district' : 'district',
      'Empty district name not allowed' : 'Empty district name not allowed',
      'address' : 'address',
      'Empty address name not allowed' : 'Empty address name not allowed',
      'SUCCESS' : 'SUCCESS',
      'Neighborhood successfully added!' : 'Neighborhood successfully added!',
      'Create' : 'Create',
      'Create Task' : 'Create Task',
      'title' : 'title',
      'Empty titles not allowed' : 'Empty titles not allowed',
      'Write task description here' : 'Write task description here',
      'Too large text' : 'Too large text',
      'Start Date' : 'Start Date',
      'Please choose start date' : 'Please choose start date',
      'End Date' : 'End Date',
      'Please choose end date' : 'Please choose end date',
      'end date should be ahead of start date' : 'end date should be ahead of start date',
      'Task successfully added!' : 'Task successfully added!',
      'Create Subtask' : 'Create Subtask',
      'Write subtask description here' : 'Write subtask description here',
      'Select Assignee' : 'Select Assignee',
      'Select' : 'Select',
      'Please select assignee' : 'Please select assignee',
      'Subtask successfully added!' : 'Subtask successfully added!',
      'item ' : 'item ',
      'car ' : 'car ',
      'Search for' : 'Search for',
      'No matches found' : 'No matches found',
      'Subtasks' : 'Subtasks',
      'Description' : 'Description',
      'Assignee' : 'Assignee',
      'IN PROGRESS' : 'IN PROGRESS',
      'DONE' : 'DONE',
      'MY TASKS' : 'MY TASKS',
      'ALL TASKS' : 'ALL TASKS',
      'User successfully Registered!' : 'User successfully Registered!',
    },
    'ge': {
      'Welcome': 'კეთილი იყოს თქვენი მობრძანება',
      'Username': 'მომხმარებლის სახელი',
      'Empty usernames not allowed' : 'ცარიელი მომხმარებლის სახელი დაუშვებელია',
      'Password' : 'პაროლი',
      'Empty password not allowed': 'ცარიელი პაროლი დაუშვებელია',
      'wrong username or password': 'პაროლი ან მომხმარებლის სახელი არასწორია',
      'Sign in' : 'შესვლა',
      'Don\'t have an account?' : 'არ გაქვთ ანგარიში?',
      'Sign up' : 'რეგისტრაცია',
      'Register' : 'რეგისტრაცია',
      'First Name' : 'სახელი',
      'Empty first names not allowed' : 'ცარიელი სახელი დაუშვებელია',
      'Last Name' : 'გვარი',
      'Empty last name not allowed' : 'ცარიელი გვარი დაუშვებელია',
      'Empty username not allowed' : 'ცარიელი მომხმარებლის სახელი დაუშვებელია',
      'username exists' : 'მომსმარებლსი სახელი არსებობს',
      'Mobile' : 'მობილურის ნომერი',
      'invalid phone number' : 'ნომერი არასწორი ფორმატისაა',
      'Repeat password' : 'გაიმეორეთ პაროლი',
      'Passwords don\'t match' : 'შეყვანილი პაროლები ერთმანეთს არ ემთხვევა',
      'Neighborhoods' : 'სამეზობლოები',
      'Profile' : 'პროფილი',
      'Sign Out' : 'გამოსვლა',
      'MY NEIGHBORHOODS' : 'ჩემი სამეზობლოები',
      'OTHER NEIGHBORHOODS' : 'სხვა სამეზობლოები',
      'SEND REQUEST' : 'მოთხოვნის გაგზავნა',
      'PENDING' : 'მოთხოვნა გაგზავნილია',
      'GENERAL INFO' : 'ზოგადი ინფორმაცია',
      'ITEMS' : 'ნივთები',
      'USERNAME' : 'მომხმარებლის სახელი',
      'FIRST NAME' : 'სახელი',
      'LAST NAME' : 'გვარი',
      'PHONE NUMBER' : 'მობილურის ნომერი',
      'Edit' : 'ცვლილება',
      'SAVE' : 'დამახსოვრება',
      'Wrong Number' : 'არასწორი ნომერი',
      'Malformed phone number' : 'ნომერს არასწორი ფორმატი აქვს',
      'ADD' : 'დამატება',
      'CANCEL' : 'გაუქმება',
      'CAR PLATE NUMBER' : 'მანქანის ნომერი',
      'Invalid Action' : 'არასწორი ქმედება',
      'Add Item' : 'ნივთის დამატება',
      'Add new item' : 'დაამატეთ ახალი ნივთი',
      'Item name' : 'ნივთის სახელი',
      'Delete Item' : 'ნივთის წაშლა',
      'Do you really want to remove this item?' : 'ნამდვილად გსურთ ამ ნივთის წაშლა?',
      'Yes' : 'დიახ',
      'No' : 'არა',
      'malformed plate number' : 'მანქანის ნომერი არასწორი ფორმატისაა',
      'Requests' : 'მოთხოვნები',
      'Profile' : 'პროფილი',
      'Tasks' : 'დავალებები',
      'Search Items' : 'ნივთის ძებნა',
      'Search Car' : 'მანქანის ძებნა',
      'What\'s on your mind? ' : 'რას ფიქრობ?',
      'Post' : 'დაპოსტვა',
      'Write your comment here' : 'დაწერეთ კომენტარი',
      ' wants to join the neighborhood' : ' სურს სამეზობლოში გაწევრიანება',
      'ACCEPT' : 'დადასტურება',
      'REJECT' : 'უარყოფა',
      'REJECTED' : 'უარყოფილია',
      'ACCEPTED' : 'დადასტურებულია',
      'Create Neighborhood' : 'სამეზობლოს შექმნა',
      'Name' : 'სახელი',
      'Empty names not allowed' : 'ცარიელი სახელი დაუშვებელია',
      'neighborhood already exists' : 'ასეთი სახელის მქონე სამეზობლო უკვე არსებობს',
      'city' : 'ქალაქი',
      'Empty ciy names not allowed' : 'ცარიელი ქალაქის სახელი დაუშვებელია',
      'district' : 'რეგიონი',
      'Empty district name not allowed' : 'ცარიელი რეგიონი დაუშვებელია',
      'address' : 'მისამართი',
      'Empty address name not allowed' : 'ცარიელი მისამართი დაუშვებელია',
      'SUCCESS' : 'მოქმედება წარმატებით განხორციელდა',
      'Neighborhood successfully added!' : 'სამეზობლო წარმატებით დაემატა',
      'Create' : 'შექმნა',
      'Create Task' : 'დავალების შექმნა',
      'title' : 'სათაური',
      'Empty titles not allowed' : 'ცარიელი სათაური დაუშვებელია',
      'Write task description here' : 'დავალების აღწერა',
      'Too large text' : 'ტექსტი ზედმეტად დიდია',
      'Start Date' : 'დაწყების თარიღი',
      'Please choose start date' : 'გთხოვთ აირჩიოთ დაწყების თარიღი',
      'End Date' : 'დასრულების თარიღი',
      'Please choose end date' : 'გთხოვთ აირჩიოთ დასრულების თარიღი',
      'end date should be ahead of start date' : 'დასრულების თარიღი უნდა იყოს დაწყების თარიღზე მეტი',
      'Task successfully added!' : 'დავალება წარმატებით დაემატა!',
      'Create Subtask' : 'ქვედავალების შექმნა',
      'Write subtask description here' : 'ქვედავალების აღწერა',
      'Select Assignee' : 'პასუხისმგებელი პირი',
      'Select' : 'აირჩიეთ',
      'Please select assignee' : 'გთხოვთ მიუთითოთ პასუხისმგებელი პირი',
      'Subtask successfully added!' : 'ქვედავალება წარმატებით დაემატა',
      'item ' : 'ნივთი ',
      'car ' : 'მანქანა',
      'Search for' : 'მოძებნე',
      'No matches found' : 'შედეგი ვერ მოიძებნა',
      'Subtasks' : 'ქვედავალებები',
      'Description' : 'აღწერა',
      'Assignee' : 'პასუხისმგებელი',
      'IN PROGRESS' : 'პროგრესშია',
      'DONE' : 'შესრულებულია',
      'MY TASKS' : 'ჩემი დავალებები',
      'ALL TASKS' : 'ყველა დავალება',
      'User successfully Registered!' : 'მომხმარებელი წარმატებით დარეგისტრირდა'
    },
  };


  static String getLanguage() {
    return _language;
  }

  static setLanguage(String language) {
    _prefs.setString('lang', language);
    _language = language;
  }

  static getValue(String name) {
    return values[_language][name];
  }

}